# Generated by Django 4.2.6 on 2023-10-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
    ]
